---
- hosts: all
  gather_facts: false
  tasks:
    # Install Python 3 on CentOS 7 and 8, thus is just temporary
    - name: Install Python 3 when it is not present
      raw: test -e /usr/bin/python3 || (yum -y install python3)
      become: true
      changed_when: false

- hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  vars:
    cloud_platform: docker
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: marvel-nccr.aiida
      vars:
        aiida_components:
          - computers
          # - plugins
          - pseudopotentials
          - examples
